### ISSUE TITLE
AWS: ensure IAM instance profile can access PAS buckets

### ISSUE THREAD

**Issue by zmb3** [pivotal/paving#46]
On AWS we recommend using S3 as a blobstore for anything other than small, non-production deployments.

For those who wish to use S3 along with IAM instance profiles instead of access/secret keys, the ops-manager profile needs access to the PAS buckets, a la:

https://github.com/pivotal-cf/terraforming-aws/blob/8e88e609cc8cd26be4fb02f8023db683b8868c3c/modules/pas/templates/iam_pas_buckets_policy.json#L11-L18

It looks like we only provide access to the ops manager buckets right now:

https://github.com/pivotal/paving/blob/33917e97848062c2db8c3104fe0d487477e32ecc/aws/ops-manager.tf#L106-L107

**Comment by zmb3** [comment]
Edit: the ops-manager role is not used by default.  You would need to use a VM extension to associate the cloud controller VMs with the role.  Given this info, if the terraform is to support this config, it probably makes sense to have a _separate_ instance profile for PAS bucket access, rather than using the ops manager one which has many more permissions.

**Comment by sneal** [comment]
Looking at how I did this before with the old terraforming-aws templates and we use a separate instance profile for all the reasons @zmb3 mentioned. That instance profile is assigned to the cloud controller and diego VMs only.

director.yml
```
vmextensions-configuration:
  - name: blobstore-iam-instance-profile
    cloud_properties:
      iam_instance_profile: ((vm_extension_iam_instance_profile))
```

pas.yml
```
  cloud_controller:
    additional_vm_extensions: blobstore-iam-instance-profile
    instance_type:
      id: ((cloud_controller_instance_type))
    instances: ((cloud_controller_instances))
    max_in_flight: ((cloud_controller_max_in_flight))
  diego_cell:
    additional_vm_extensions: ((diego_cell_additional_vm_extensions))
    instance_type:
      id: ((diego_cell_instance_type))
    instances: ((diego_cell_instances))
    max_in_flight: ((diego_cell_max_in_flight))
```

While I think using instance profiles over keys is always preferred, it's certainly more complicated (no GUI support) and there are cases where instance profiles aren't supported (MySQL tile etc). This _might_ be something we add to the paving-extensions versus here.
